// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMSokw9H2LZnkSRyjJzd_l1xlEQgcOTfU',
    appId: '1:21901023629:web:163dee4627e32833da05c4',
    messagingSenderId: '21901023629',
    projectId: 'flutter-login-playground',
    authDomain: 'flutter-login-playground.firebaseapp.com',
    storageBucket: 'flutter-login-playground.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-nxuLTUAp5R62rNrnxpNY7Rp3LlKcwcE',
    appId: '1:21901023629:android:776069e120446dafda05c4',
    messagingSenderId: '21901023629',
    projectId: 'flutter-login-playground',
    storageBucket: 'flutter-login-playground.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAglGM1LwinFxB6w4xcJD458LXg8w6HjU8',
    appId: '1:21901023629:ios:117c4f8d2ca89521da05c4',
    messagingSenderId: '21901023629',
    projectId: 'flutter-login-playground',
    storageBucket: 'flutter-login-playground.appspot.com',
    iosClientId: '21901023629-5iuib8ttj7r5don0gjpmufibdg3lm5ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPlayground',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAglGM1LwinFxB6w4xcJD458LXg8w6HjU8',
    appId: '1:21901023629:ios:117c4f8d2ca89521da05c4',
    messagingSenderId: '21901023629',
    projectId: 'flutter-login-playground',
    storageBucket: 'flutter-login-playground.appspot.com',
    iosClientId: '21901023629-5iuib8ttj7r5don0gjpmufibdg3lm5ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginPlayground',
  );
}
